/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-05-10 23:34:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import Conexion.*;
import Modelo.Producto;
import java.util.Vector;

public final class Catalogo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

 Vector<Producto> productos; 

Conexion miconexion;
Connection con;
Statement stmt;
ResultSet rs;
String id,nombre,precio,imagen,cantidad;
int i=0;

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("Conexion");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.util.Vector");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("Modelo.Producto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
 HttpSession sesion = request.getSession(true); 
      out.write('\n');
      out.write('\n');
 productos = new Vector<Producto>();
      out.write('\n');
 if(sesion.isNew() || sesion==null)
    {
    response.sendRedirect("index.jsp");
    return;
    }
else{
    if(sesion.getAttribute("sesionProd")==null)
        {
        sesion.setAttribute("sesionProd",productos);
        }
    else
        {
        productos = (Vector<Producto>) sesion.getAttribute("sesionProd");
        }
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write('\n');
 
miconexion = new Conexion();
con = miconexion.getConnection();
stmt = con.createStatement();
rs = stmt.executeQuery("SELECT * FROM producto");


      out.write("\n");
      out.write("\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\" />\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\n");
      out.write("           <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <meta name=\"description\" content=\"\" />\n");
      out.write("        <meta name=\"author\" content=\"\" />\n");
      out.write("        <title>Catalogo</title>\n");
      out.write("        <!-- Favicon-->\n");
      out.write("        <link rel=\"icon\" type=\"image/x-icon\" href=\"assets/favicon.ico\" />\n");
      out.write("        <!-- Bootstrap icons-->\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css\" rel=\"stylesheet\" />\n");
      out.write("        <!-- Core theme CSS (includes Bootstrap)-->\n");
      out.write("        <link href=\"css/styles.css\" rel=\"stylesheet\" />\n");
      out.write("    </head>\n");
      out.write("    <body class=\"d-flex flex-column\">\n");
      out.write("        <main class=\"flex-shrink-0\">\n");
      out.write("            <!-- Navigation-->\n");
      out.write("            <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\n");
      out.write("                <div class=\"container px-5\">\n");
      out.write("                    <a class=\"navbar-brand\" href=\"index.html\">Catalogo</a>\n");
      out.write("                    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\"><span class=\"navbar-toggler-icon\"></span></button>\n");
      out.write("                    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("                        <ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\n");
      out.write("                            <li class=\"nav-item\"><a class=\"nav-link\" href=\"index.html\">Home</a></li>\n");
      out.write("                          \n");
      out.write("                            <li class=\"nav-item\"><a class=\"nav-link\" href=\"Carrito.html\">Carrito</a></li>\n");
      out.write("                            <li class=\"nav-item\"><a class=\"nav-link\" href=\"Filtros.html\">Filtros</a></li>\n");
      out.write("                            <li class=\"nav-item dropdown\">\n");
      out.write("                                <a class=\"nav-link dropdown-toggle\" id=\"navbarDropdownBlog\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">Log in</a>\n");
      out.write("                                <ul class=\"dropdown-menu dropdown-menu-end\" aria-labelledby=\"navbarDropdownBlog\">\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"registro.html\">Registro</a></li>\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"login.html\">Log in</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("                           \n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </nav>\n");
      out.write("            <!-- Header-->\n");
      out.write("            <div class=\"container px-5\">\n");
      out.write("            <div class=\"row justify-content-center\">\n");
      out.write("             <table>\n");
      out.write("            <tr>\n");
      out.write("                ");
 while(rs.next())
                    {
                    imagen = rs.getString("pro_imagen");
                    id = rs.getString("pro_codigo");
                    nombre = rs.getString("pro_nombre");
                    precio = rs.getString("pro_precio");
                    cantidad = rs.getString("pro_existencia");
                
      out.write("\n");
      out.write("                <td>\n");
      out.write("                    <img src=\"");
      out.print(imagen);
      out.write("\" width=\"100\" height=\"100\">\n");
      out.write("                    <br>Codigo: ");
      out.print(id);
      out.write("\n");
      out.write("                    <br>Descripción: ");
      out.print(nombre);
      out.write("\n");
      out.write("                    <br>Precio: ");
      out.print(precio);
      out.write("\n");
      out.write("                    <br>Cantidad: ");
      out.print(cantidad);
      out.write("\n");
      out.write("                    <form name=\"miformulario\" action=\"carrito.jsp\" method = \"post\">\n");
      out.write("                        <input type=\"hidden\" name=\"id\" value=\"");
      out.print(id);
      out.write("\">\n");
      out.write("                        <input type=\"hidden\" name=\"nombre\" value=\"");
      out.print(nombre);
      out.write("\">\n");
      out.write("                        <input type=\"hidden\" name=\"precio\" value=\"");
      out.print(precio);
      out.write("\">\n");
      out.write("                        <input type=\"hidden\" name=\"cantidad\" value=\"");
      out.print(cantidad);
      out.write("\">\n");
      out.write("                        <input type=\"hidden\" name=\"imagen\" value=\"");
      out.print(imagen);
      out.write("\">\n");
      out.write("                        <input type=\"submit\" value=\"Agregar a Carrito\">\n");
      out.write("                        \n");
      out.write("                    </form>\n");
      out.write("                </td>\n");
      out.write("                ");
 i++;
                    if (i==4)
                        {
      out.write("\n");
      out.write("                         </tr> <tr>\n");
      out.write("                        ");
 i=0;
                        }
                    
                 } i=0; 
      out.write("\n");
      out.write("            </tr>            \n");
      out.write("        </table>\n");
      out.write("            </div>\n");
      out.write("            </div>\n");
      out.write("        <!-- Footer-->\n");
      out.write("        <footer class=\"bg-dark py-4 mt-auto\">\n");
      out.write("            <div class=\"container px-5\">\n");
      out.write("                <div class=\"row align-items-center justify-content-between flex-column flex-sm-row\">\n");
      out.write("                    <div class=\"col-auto\"><div class=\"small m-0 text-white\">Copyright &copy; Your Website 2022</div></div>\n");
      out.write("                    <div class=\"col-auto\">\n");
      out.write("                        <a class=\"link-light small\" href=\"#!\">Privacy</a>\n");
      out.write("                        <span class=\"text-white mx-1\">&middot;</span>\n");
      out.write("                        <a class=\"link-light small\" href=\"#!\">Terms</a>\n");
      out.write("                        <span class=\"text-white mx-1\">&middot;</span>\n");
      out.write("                        <a class=\"link-light small\" href=\"#!\">Contact</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </footer>\n");
      out.write("        <!-- Bootstrap core JS-->\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("        <!-- Core theme JS-->\n");
      out.write("        <script src=\"js/scripts.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
